
package vista;

import java.sql.Connection;//conexion a BD
import java.sql.DriverManager;//driver de conexion
import java.sql.ResultSet;//resultado final de datos
import java.sql.ResultSetMetaData;//resultado de metadatos
import java.sql.SQLException;//Tratamiento de Errros de BD SQL
import java.sql.Statement;//Generador de sentencias SQL    DDL,DML,DCL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//fecha de sistema
import javax.swing.ImageIcon;//Tratamiento de imagenes
import javax.swing.JOptionPane;//ventanas emergentes
import javax.swing.table.DefaultTableModel;
import modelo.Flor;


public class EditarFlor extends javax.swing.JFrame {
    
    public Connection cn;
    public Statement stmt;
    public ResultSet rs;
    
    
    Flor objFlor = new Flor();

   
    public EditarFlor() {
        initComponents();
    }
    
    
    public void conectarBase(){
    try{ 
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost/bdflowerstudiovmz","uismeneses","udl123");
            stmt=cn.createStatement();
    }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error de base de datos 1: \n"+ ex);
    }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error de base de datos 2:"+ e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panGeneral = new javax.swing.JPanel();
        lblImgDecor1 = new javax.swing.JLabel();
        lblImgDecor2 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        panEditar = new javax.swing.JPanel();
        lblIdEditar = new javax.swing.JLabel();
        lblNombreEditar = new javax.swing.JLabel();
        lblExistenciaEditar = new javax.swing.JLabel();
        lblPrecioEditar = new javax.swing.JLabel();
        txtNombreEditar = new javax.swing.JTextField();
        txtIdEditar = new javax.swing.JTextField();
        txtExistenciaEditar = new javax.swing.JTextField();
        txtPrecioEditar = new javax.swing.JTextField();
        btnBuscarFlor = new javax.swing.JButton();
        btnEditarFlor = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        panEliminar = new javax.swing.JPanel();
        txtFlorEliminar = new javax.swing.JTextField();
        btnEliminarFlor = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panGeneral.setBackground(new java.awt.Color(255, 153, 255));

        lblImgDecor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bouquet_PNG6-removebg-preview.png"))); // NOI18N

        lblImgDecor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png-transparent-grass-presentation-computer-wallpaper-grass-removebg-preview.png"))); // NOI18N

        lblEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 0, 102));
        lblEliminar.setText("¿Deseas Eliminar Alguna Flor?");

        panEditar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panEditar.setOpaque(false);

        lblIdEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblIdEditar.setForeground(new java.awt.Color(255, 0, 102));
        lblIdEditar.setText("ID:");

        lblNombreEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNombreEditar.setForeground(new java.awt.Color(255, 0, 102));
        lblNombreEditar.setText("Nombre:");

        lblExistenciaEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblExistenciaEditar.setForeground(new java.awt.Color(255, 0, 102));
        lblExistenciaEditar.setText("Existencia:");

        lblPrecioEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPrecioEditar.setForeground(new java.awt.Color(255, 0, 102));
        lblPrecioEditar.setText("Precio:");

        txtNombreEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtIdEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtExistenciaEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtPrecioEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        btnBuscarFlor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-flat-removebg-preview.png"))); // NOI18N
        btnBuscarFlor.setOpaque(false);
        btnBuscarFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFlorActionPerformed(evt);
            }
        });

        btnEditarFlor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images__1_-removebg-preview.png"))); // NOI18N
        btnEditarFlor.setOpaque(false);
        btnEditarFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFlorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEditarLayout = new javax.swing.GroupLayout(panEditar);
        panEditar.setLayout(panEditarLayout);
        panEditarLayout.setHorizontalGroup(
            panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEditarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEditarLayout.createSequentialGroup()
                        .addComponent(lblPrecioEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEditarLayout.createSequentialGroup()
                        .addComponent(btnBuscarFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(panEditarLayout.createSequentialGroup()
                        .addComponent(lblIdEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panEditarLayout.createSequentialGroup()
                        .addComponent(lblNombreEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panEditarLayout.createSequentialGroup()
                        .addComponent(lblExistenciaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(txtExistenciaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        panEditarLayout.setVerticalGroup(
            panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdEditar)
                    .addComponent(txtIdEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEditar)
                    .addComponent(txtNombreEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExistenciaEditar)
                    .addComponent(txtExistenciaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioEditar)
                    .addComponent(txtPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        lblEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 0, 102));
        lblEditar.setText("¿Que Flor Desea Editar del Inventario?");

        panEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escribe el ID de la flor que quieres eliminar.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 11), new java.awt.Color(255, 0, 102))); // NOI18N
        panEliminar.setOpaque(false);

        txtFlorEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtFlorEliminar.setForeground(new java.awt.Color(51, 51, 51));

        btnEliminarFlor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-icon-png-19-removebg-preview.png"))); // NOI18N
        btnEliminarFlor.setOpaque(false);
        btnEliminarFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFlorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEliminarLayout = new javax.swing.GroupLayout(panEliminar);
        panEliminar.setLayout(panEliminarLayout);
        panEliminarLayout.setHorizontalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarLayout.createSequentialGroup()
                .addGroup(panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEliminarLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(txtFlorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panEliminarLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnEliminarFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panEliminarLayout.setVerticalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFlorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/190238-removebg-preview.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGeneralLayout = new javax.swing.GroupLayout(panGeneral);
        panGeneral.setLayout(panGeneralLayout);
        panGeneralLayout.setHorizontalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgDecor1)
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgDecor2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(panEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                    .addContainerGap(341, Short.MAX_VALUE)
                    .addComponent(lblEditar)
                    .addGap(84, 84, 84)))
        );
        panGeneralLayout.setVerticalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(panEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImgDecor2))
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgDecor1))
            .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panGeneralLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFlorActionPerformed
       int confirmaBaja;
        try {
            conectarBase();
            int idFlorBaja=Integer.parseInt(txtFlorEliminar.getText());
            confirmaBaja=stmt.executeUpdate("DELETE FROM Flor where id = '"+idFlorBaja+"'");
            
            if (confirmaBaja==1) {
                JOptionPane.showMessageDialog(null, "Se dio de baja el ID de la flor\n"+idFlorBaja+"\nVerifica consulta");
            } else {
                JOptionPane.showMessageDialog(null, "Error no existe el ID del Libro!!!");
            }
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Error 5 de BD para Baja :\n\n"+ ex);
        }
    }//GEN-LAST:event_btnEliminarFlorActionPerformed

    private void btnBuscarFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFlorActionPerformed
        try {
            conectarBase();
            objFlor.setId(Integer.parseInt(txtIdEditar.getText()));
            rs=stmt.executeQuery("SELECT * FROM flor where id = '"+objFlor.getId()+"'");
            JOptionPane.showMessageDialog(null, "Buscando Flor, por favor espere...");
            
            if (rs.next()==true) {
                txtNombreEditar.setText(rs.getString("nombre"));
                txtExistenciaEditar.setText(rs.getString("existencia"));
                txtPrecioEditar.setText(rs.getString("precio"));
            } else {
                JOptionPane.showMessageDialog(null, "Error, no existe el ID de esta Flor");
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error 6 de BD para Baja :\n\n"+ ex);
        }
    }//GEN-LAST:event_btnBuscarFlorActionPerformed

    private void btnEditarFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFlorActionPerformed
        String actualizarFlor="";
        try {
            conectarBase();
            objFlor.setId(Integer.parseInt(txtIdEditar.getText()));
            objFlor.setNombre(txtNombreEditar.getText());
            objFlor.setExistencia(txtExistenciaEditar.getText());
            objFlor.setPrecio(txtPrecioEditar.getText());
            
            actualizarFlor="UPDATE flor SET nombre = '"+objFlor.getNombre()+"', existencia = '"+objFlor.getExistencia()+"', precio = '"+objFlor.getPrecio()+"' where id= '"+objFlor.getId()+"'";
            stmt.executeUpdate(actualizarFlor);
            JOptionPane.showMessageDialog(null, "Datos de la flor actualizados\n de forma correcta \n\nVerifica consulta");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de BD 7 editar \n\n" + ex);
            
        }
    }//GEN-LAST:event_btnEditarFlorActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu ventanaMenu = new Menu();
        ventanaMenu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFlor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFlor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFlor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFlor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarFlor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFlor;
    private javax.swing.JButton btnEditarFlor;
    private javax.swing.JButton btnEliminarFlor;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblExistenciaEditar;
    private javax.swing.JLabel lblIdEditar;
    private javax.swing.JLabel lblImgDecor1;
    private javax.swing.JLabel lblImgDecor2;
    private javax.swing.JLabel lblNombreEditar;
    private javax.swing.JLabel lblPrecioEditar;
    private javax.swing.JPanel panEditar;
    private javax.swing.JPanel panEliminar;
    private javax.swing.JPanel panGeneral;
    private javax.swing.JTextField txtExistenciaEditar;
    private javax.swing.JTextField txtFlorEliminar;
    private javax.swing.JTextField txtIdEditar;
    private javax.swing.JTextField txtNombreEditar;
    private javax.swing.JTextField txtPrecioEditar;
    // End of variables declaration//GEN-END:variables

    private String String(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
