
package vista;

import java.sql.Connection;//conexion a BD
import java.sql.DriverManager;//driver de conexion
import java.sql.ResultSet;//resultado final de datos
import java.sql.ResultSetMetaData;//resultado de metadatos
import java.sql.SQLException;//Tratamiento de Errros de BD SQL
import java.sql.Statement;//Generador de sentencias SQL    DDL,DML,DCL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//fecha de sistema
import javax.swing.ImageIcon;//Tratamiento de imagenes
import javax.swing.JOptionPane;//ventanas emergentes
import modelo.Flor;


public class IngresarNueva extends javax.swing.JFrame {
    
    public Connection cn;
    public Statement stmt;
    public ResultSet rs;
    
    Flor objFlor = new Flor();

    
    public IngresarNueva() {
        initComponents();
    }
    
    
    public void conectarBase(){
    try{ 
            Class.forName("com.mysql.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost/bdflowerstudiovmz","uismeneses","udl123");
            stmt=cn.createStatement();
    }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error de base de datos 1: \n"+ ex);
    }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error de base de datos 2:"+ e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        lblImgDecor1 = new javax.swing.JLabel();
        lblImgDecor2 = new javax.swing.JLabel();
        lblImgDecor3 = new javax.swing.JLabel();
        lblImgDecor4 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblImgDecor5 = new javax.swing.JLabel();
        panDatos = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombreFlor = new javax.swing.JLabel();
        lblExistencia = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombreFlor = new javax.swing.JTextField();
        txtExistencia = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnRegistrarFlor = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrincipal.setBackground(new java.awt.Color(153, 255, 255));

        lblImgDecor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/458-4585133_flores-formato-png-clipart-transparent-png-download-removebg-preview.png"))); // NOI18N

        lblImgDecor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagenes-de-flores-de-caricatura-11562884881pao2zavgwc-removebg-preview.png"))); // NOI18N

        lblImgDecor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/424-4243689_guia-flores-png-transparent-png-png-download-gua-removebg-preview.png"))); // NOI18N

        lblImgDecor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/56-560438_flores-mexicanas-png-transparent-png-removebg-preview.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 51, 204));
        lblTitulo.setText("Ingresa Flor");

        lblImgDecor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagenes-de-flores-de-caricatura-11562884881pao2zavgwc-removebg-preview.png"))); // NOI18N

        panDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresa los datos de la flor.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(255, 0, 204))); // NOI18N
        panDatos.setForeground(new java.awt.Color(255, 51, 204));
        panDatos.setOpaque(false);

        lblId.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 0, 153));
        lblId.setText("ID:");

        lblNombreFlor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblNombreFlor.setForeground(new java.awt.Color(255, 0, 153));
        lblNombreFlor.setText("Nombre:");

        lblExistencia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblExistencia.setForeground(new java.awt.Color(255, 0, 153));
        lblExistencia.setText("Existencia:");

        lblPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 0, 153));
        lblPrecio.setText("Precio:");

        txtId.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtNombreFlor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtExistencia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        btnRegistrarFlor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon-png-10-removebg-preview.png"))); // NOI18N
        btnRegistrarFlor.setOpaque(false);
        btnRegistrarFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFlorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panDatosLayout = new javax.swing.GroupLayout(panDatos);
        panDatos.setLayout(panDatosLayout);
        panDatosLayout.setHorizontalGroup(
            panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosLayout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosLayout.createSequentialGroup()
                        .addComponent(lblExistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosLayout.createSequentialGroup()
                        .addComponent(lblNombreFlor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosLayout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarFlor)
                .addGap(113, 113, 113))
        );
        panDatosLayout.setVerticalGroup(
            panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFlor)
                    .addComponent(txtNombreFlor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExistencia)
                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnRegistrarFlor)
                .addContainerGap())
        );

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/190238-removebg-preview.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgDecor1)
                    .addComponent(lblImgDecor4))
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                                .addComponent(panDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgDecor3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImgDecor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                        .addComponent(lblImgDecor5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(lblImgDecor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgDecor4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(lblImgDecor2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImgDecor5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgDecor3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFlorActionPerformed
       conectarBase();
       
       objFlor.setId(Integer.parseInt(txtId.getText()));
       objFlor.setNombre(txtNombreFlor.getText());
       objFlor.setExistencia(txtExistencia.getText());
       objFlor.setPrecio(txtPrecio.getText());
       
       
       String altaFlor="INSERT INTO FLOR (`id`,`nombre`,`existencia`,`precio`) VALUES ('"+objFlor.getId()+"','"+objFlor.getNombre()+"','"+objFlor.getExistencia()+"','"+objFlor.getPrecio()+"')";
       
        try {
            stmt.executeUpdate(altaFlor);
            JOptionPane.showMessageDialog(null, "Registro exitoso de:\n "+objFlor.getNombre());
            this.txtId.setText("");
        this.txtNombreFlor.setText("");
        this.txtExistencia.setText(null);
        this.txtPrecio.setText(null);
        
        this.txtId.requestFocus(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error 3 de BD para Alta :\n\n"+ e);
        }
    }//GEN-LAST:event_btnRegistrarFlorActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Menu ventanaMenu = new Menu();
        ventanaMenu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarFlor;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblExistencia;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImgDecor1;
    private javax.swing.JLabel lblImgDecor2;
    private javax.swing.JLabel lblImgDecor3;
    private javax.swing.JLabel lblImgDecor4;
    private javax.swing.JLabel lblImgDecor5;
    private javax.swing.JLabel lblNombreFlor;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panDatos;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreFlor;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
