
package vista;


public class Menu extends javax.swing.JFrame {

   
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panGeneral = new javax.swing.JPanel();
        lblTituloAccion = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblImgDecor1 = new javax.swing.JLabel();
        lblImgDecor2 = new javax.swing.JLabel();
        lblImgDecor3 = new javax.swing.JLabel();
        btnPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(699, 514));

        panGeneral.setBackground(new java.awt.Color(255, 255, 153));

        lblTituloAccion.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTituloAccion.setForeground(new java.awt.Color(0, 204, 51));
        lblTituloAccion.setText("¿Que acción deseas realizar?");

        btnIngresar.setBackground(new java.awt.Color(153, 255, 153));
        btnIngresar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(51, 51, 51));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-icon-png-10-removebg-preview.png"))); // NOI18N
        btnIngresar.setText("Ingresar Nueva Flor");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(51, 51, 51));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flowers-removebg-preview.png"))); // NOI18N
        btnConsultar.setText("Consultar Inventario de Flores");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(153, 255, 153));
        btnEditar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(51, 51, 51));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/depositphotos_214300794-stock-illustration-flower-icon-vector-isolated-on-removebg-preview.png"))); // NOI18N
        btnEditar.setText("Editar o Eliminar Informacion de Flor");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(153, 255, 153));
        btnClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(51, 51, 51));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/people-people-icon-blue-11553450975ccznm1rxwu-removebg-preview.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3094700-removebg-preview-removebg-preview.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblImgDecor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/141-1416345_flores-png-primavera-ramo-de-flores-png-transparent-removebg-preview-removebg-preview.png"))); // NOI18N

        lblImgDecor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kisspng-wedding-invitation-watercolour-flowers-purple-clip-watercolor-flower-5abb24598458f0.7421615315222139775421-removebg-preview.png"))); // NOI18N

        lblImgDecor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/195-1950245_flower-png-butterfly-corner-png-transparent-png-removebg-preview.png"))); // NOI18N

        btnPedidos.setBackground(new java.awt.Color(153, 255, 153));
        btnPedidos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(51, 51, 51));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/679821-removebg-preview.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGeneralLayout = new javax.swing.GroupLayout(panGeneral);
        panGeneral.setLayout(panGeneralLayout);
        panGeneralLayout.setHorizontalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addComponent(lblImgDecor1)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnIngresar))
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultar)
                            .addComponent(lblTituloAccion))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgDecor2))
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panGeneralLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnSalir))
                            .addGroup(panGeneralLayout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(btnEditar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientes)
                        .addGap(61, 61, 61)
                        .addComponent(btnPedidos)
                        .addGap(37, 37, 37)))
                .addComponent(lblImgDecor3))
        );
        panGeneralLayout.setVerticalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblImgDecor1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblImgDecor2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblTituloAccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresar)
                        .addGap(12, 12, 12)))
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblImgDecor3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnConsultar)
                        .addGap(28, 28, 28)
                        .addComponent(btnEditar)
                        .addGap(32, 32, 32)
                        .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClientes)
                            .addComponent(btnPedidos))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Acceso ventanaAcceso = new Acceso();
        ventanaAcceso.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        IngresarNueva ventanaIngreso = new IngresarNueva();
        ventanaIngreso.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ConsultaFlores ventanaConsulta = new ConsultaFlores();
        ventanaConsulta.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        EditarFlor ventanaEditar= new EditarFlor();
        ventanaEditar.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        GestionClientes ventanaGestionClientes= new GestionClientes();
        ventanaGestionClientes.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        Pedidos ventanaPedidos= new Pedidos();
        ventanaPedidos.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblImgDecor1;
    private javax.swing.JLabel lblImgDecor2;
    private javax.swing.JLabel lblImgDecor3;
    private javax.swing.JLabel lblTituloAccion;
    private javax.swing.JPanel panGeneral;
    // End of variables declaration//GEN-END:variables
}
